In [1]:
!pip install tensorflow

In [2]:
import numpy as np

In [3]:
from numpy import genfromtxt
data= genfromtxt('Downloads/bank_note_data.txt',  delimiter =',')

In [4]:
data

array([[  3.6216 ,   8.6661 ,  -2.8073 ,  -0.44699,   0.     ],
       [  4.5459 ,   8.1674 ,  -2.4586 ,  -1.4621 ,   0.     ],
       [  3.866  ,  -2.6383 ,   1.9242 ,   0.10645,   0.     ],
       ...,
       [ -3.7503 , -13.4586 ,  17.5932 ,  -2.7771 ,   1.     ],
       [ -3.5637 ,  -8.3827 ,  12.393  ,  -1.2823 ,   1.     ],
       [ -2.5419 ,  -0.65804,   2.6842 ,   1.1952 ,   1.     ]])

In [5]:
# i want to extract the fouth column
labels = data[:,4]

In [6]:
labels

array([0., 0., 0., ..., 1., 1., 1.])

In [7]:
# i want to extract all 0-3 columns into features
features = data[:,0:4]

In [8]:
features

array([[  3.6216 ,   8.6661 ,  -2.8073 ,  -0.44699],
       [  4.5459 ,   8.1674 ,  -2.4586 ,  -1.4621 ],
       [  3.866  ,  -2.6383 ,   1.9242 ,   0.10645],
       ...,
       [ -3.7503 , -13.4586 ,  17.5932 ,  -2.7771 ],
       [ -3.5637 ,  -8.3827 ,  12.393  ,  -1.2823 ],
       [ -2.5419 ,  -0.65804,   2.6842 ,   1.1952 ]])

In [9]:
X = features
y = labels

# Train Test Split

In [10]:
from sklearn.model_selection import train_test_split

In [11]:
# random_state is used to control the shuffling of data before splitting it into training and testing sets
X_train, X_test, y_train, y_test= train_test_split(X, y, test_size = 0.3, random_state=0)

In [12]:
len(X_train)

960

In [13]:
len(X)

1372

In [14]:
len(X_test)

412

In [15]:
#y_test

# Standardization of the Data
we do it to avoid the biasness and to overcome the computational cost

In [16]:
from sklearn.preprocessing import MinMaxScaler

In [17]:
#define minmaxscaler with variable
scaler_object = MinMaxScaler()

In [18]:
# object.fit is used to pick the maximum and minimum values in the dataset
scaler_object.fit(X_train)

MinMaxScaler()

In [19]:
# object.transform is used to divide the maximum by the positive values of the dataset
# and divide the minimum value by the nagative values in the dataset. 
# To bring all the values in a rang of [0-1] 

scaled_X_train = scaler_object.transform(X_train)

In [20]:
scaled_X_test = scaler_object.transform(X_test)
scaled_X_test

array([[0.387405  , 0.11250267, 0.66790876, 0.66254348],
       [0.89480647, 0.51420791, 0.24176708, 0.86962129],
       [0.36950035, 0.6533469 , 0.14420919, 0.38041779],
       ...,
       [0.41192468, 0.46178629, 0.31880156, 0.80177141],
       [0.45188014, 0.63507542, 0.14923213, 0.47290616],
       [1.01922031, 0.71064596, 0.11818985, 0.81402665]])

# Building a Neural Network

In [21]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [24]:
#creating a model squentially
model = Sequential()


# Dense is called fully connected layers
# 5 (Neuran)
# input_dim = how many columns or features we have 

# This is my first hidden layer
model.add(Dense(5, input_dim=4, activation='relu'))

# This is my second hidden layer
model.add(Dense(4, activation='relu'))

#whenever we have binary callification we use sigmoid 
# we must use sigmoid at the last output layers
# This is my Last output
model.add(Dense(1, activation='sigmoid'))

# Compile Model

In [25]:
# categorical_crossentropy
# best-fit methods are suitable for linear simple models...
# Adam is designed for the complex, non-linear, high-dimensional optimization
model.compile(loss = 'binary_crossentropy', optimizer= 'adam', metrics = ['accuracy'])

# Train the Model

In [26]:
model.fit(scaled_X_train, y_train, epochs=50, verbose=1)

Epoch 1/50
30/30 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.5562 - loss: 0.6691
Epoch 2/50
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5496 - loss: 0.6661
Epoch 3/50
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5748 - loss: 0.6556
Epoch 4/50
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5673 - loss: 0.6550 
Epoch 5/50
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5863 - loss: 0.6453
Epoch 6/50
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5617 - loss: 0.6559
Epoch 7/50
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5859 - loss: 0.6478
Epoch 8/50
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5938 - loss: 0.6490 
Epoch 9/50
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6520 - loss: 0.6240
Epoch 10/50
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6330 - loss: 0.6254 
Epoch 11/50
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6356 - loss: 0.6251 
Epoch 12/50
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6501 

# Evaluate the Model

In [27]:
predictions= model.predict(scaled_X_test)

13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step


In [28]:
# values less than 0.5 = 0
# values more than 0.5 = 1
predicted_classes = np.where(predictions > 0.5, 1, 0)

In [32]:
#predictions

In [33]:
from sklearn.metrics import confusion_matrix, classification_report

In [34]:
print(classification_report(y_test, predicted_classes))

              precision    recall  f1-score   support

         0.0       0.93      0.99      0.96       232
         1.0       0.98      0.91      0.95       180

    accuracy                           0.95       412
   macro avg       0.96      0.95      0.95       412
weighted avg       0.96      0.95      0.95       412

