In [1]:
pip install ucimlrepo

Note: you may need to restart the kernel to use updated packages.


In [2]:
from ucimlrepo import fetch_ucirepo 
  
# fetch dataset 
banknote_authentication = fetch_ucirepo(id=267) 
  
# data (as pandas dataframes) 
X = banknote_authentication.data.features 
y = banknote_authentication.data.targets 
  
# metadata 
print(banknote_authentication.metadata) 
  
# variable information 
print(banknote_authentication.variables) 

{'uci_id': 267, 'name': 'Banknote Authentication', 'repository_url': 'https://archive.ics.uci.edu/dataset/267/banknote+authentication', 'data_url': 'https://archive.ics.uci.edu/static/public/267/data.csv', 'abstract': 'Data were extracted from images that were taken for the evaluation of an authentication procedure for banknotes.', 'area': 'Computer Science', 'tasks': ['Classification'], 'characteristics': ['Multivariate'], 'num_instances': 1372, 'num_features': 4, 'feature_types': ['Real'], 'demographics': [], 'target_col': ['class'], 'index_col': None, 'has_missing_values': 'no', 'missing_values_symbol': None, 'year_of_dataset_creation': 2012, 'last_updated': 'Fri Feb 16 2024', 'dataset_doi': '10.24432/C55P57', 'creators': ['Volker Lohweg'], 'intro_paper': None, 'additional_info': {'summary': 'Data were extracted from images that were taken from genuine and forged banknote-like specimens.  For digitization, an industrial camera usually used for print inspection was used. The final im

# Keras Basics

Welcome to the section on deep learning! We'll be using Keras with a TensorFlow backend to perform our deep learning operations.

This means we should get familiar with some Keras fundamentals and basics!

## Imports



In [3]:
import numpy as np

## Dataset

We will use the Bank Authentication Data Set to start off with. This data set consists of various image features derived from images that had 400 x 400 pixels. You should note **the data itself that we will be using ARE NOT ACTUAL IMAGES**, they are **features** of images. In the next lecture we will cover grabbing and working with image data with Keras. This notebook focuses on learning the basics of building a neural network with Keras.

_____
More info on the data set:

https://archive.ics.uci.edu/ml/datasets/banknote+authentication

Data were extracted from images that were taken from genuine and forged banknote-like specimens. For digitization, an industrial camera usually used for print inspection was used. The final images have 400x 400 pixels. Due to the object lens and distance to the investigated object gray-scale pictures with a resolution of about 660 dpi were gained. Wavelet Transform tool were used to extract features from images.


Attribute Information:

1. variance of Wavelet Transformed image (continuous) 
2. skewness of Wavelet Transformed image (continuous) 
3. curtosis of Wavelet Transformed image (continuous) 
4. entropy of image (continuous) 
5. class (integer) 

## Reading in the Data Set

We've already downloaded the dataset, its in the DATA folder. So let's open it up. 

In [4]:
from numpy import genfromtxt
data = genfromtxt('https://archive.ics.uci.edu/static/public/267/data.csv', delimiter=',')
#delimiter added beacuse this is preloaded data so it needs such features

In [5]:
data
#0 and 1 shows authentic and false notes

array([[      nan,       nan,       nan,       nan,       nan],
       [  3.6216 ,   8.6661 ,  -2.8073 ,  -0.44699,   0.     ],
       [  4.5459 ,   8.1674 ,  -2.4586 ,  -1.4621 ,   0.     ],
       ...,
       [ -3.7503 , -13.4586 ,  17.5932 ,  -2.7771 ,   1.     ],
       [ -3.5637 ,  -8.3827 ,  12.393  ,  -1.2823 ,   1.     ],
       [ -2.5419 ,  -0.65804,   2.6842 ,   1.1952 ,   1.     ]])

In [6]:
labels = data[:,4]

In [7]:
labels

array([nan,  0.,  0., ...,  1.,  1.,  1.])

In [8]:
features = data[:,0:4]

In [9]:
features

array([[      nan,       nan,       nan,       nan],
       [  3.6216 ,   8.6661 ,  -2.8073 ,  -0.44699],
       [  4.5459 ,   8.1674 ,  -2.4586 ,  -1.4621 ],
       ...,
       [ -3.7503 , -13.4586 ,  17.5932 ,  -2.7771 ],
       [ -3.5637 ,  -8.3827 ,  12.393  ,  -1.2823 ],
       [ -2.5419 ,  -0.65804,   2.6842 ,   1.1952 ]])

In [10]:
X = features
y = labels

## Split the Data into Training and Test

Its time to split the data into a train/test set. Keep in mind, sometimes people like to split 3 ways, train/test/validation. We'll keep things simple for now. **Remember to check out the video explanation as to why we split and what all the parameters mean!**

In [11]:
from sklearn.model_selection import train_test_split

In [12]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [13]:
X_train
#show length of x_train and x_test

array([[  0.74428,  -3.7723 ,   1.6131 ,   1.5754 ],
       [  4.6464 ,  10.5326 ,  -4.5852 ,  -4.206  ],
       [ -4.3773 ,  -5.5167 ,  10.939  ,  -0.4082 ],
       ...,
       [ -3.9698 ,   3.6812 ,  -0.60008,  -4.0133 ],
       [ -5.873  ,   9.1752 ,  -0.27448,  -6.0422 ],
       [ -3.5985 , -13.6593 ,  17.6052 ,  -2.4927 ]])

In [14]:
X_test

array([[ 2.5503  , -4.9518  ,  6.3729  , -0.41596 ],
       [ 1.4276  ,  8.3847  , -2.0995  , -1.9677  ],
       [ 2.1464  ,  6.0795  , -0.5778  , -2.2302  ],
       ...,
       [ 2.2517  , -5.1422  ,  4.2916  , -1.2487  ],
       [ 5.2418  , 10.5388  , -4.1174  , -4.2797  ],
       [-0.8734  , -0.033118, -0.20165 ,  0.55774 ]])

In [15]:
y_train

array([ 1.,  0.,  1.,  0.,  0.,  1.,  0.,  0.,  1.,  0.,  0.,  0.,  1.,
        1.,  1.,  0.,  1.,  1.,  1.,  0.,  1.,  1.,  1.,  0.,  1.,  0.,
        0.,  1.,  0.,  0.,  0.,  1.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,
        1.,  0.,  0.,  1.,  0.,  0.,  1.,  1.,  1.,  0.,  0.,  0.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,
        0.,  1.,  0.,  0.,  0.,  0.,  1.,  1.,  0.,  1.,  1.,  0.,  1.,
        0.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  0.,
        1.,  0.,  0.,  0.,  0.,  1.,  1.,  1.,  0.,  0.,  0.,  1.,  0.,
        1.,  1.,  1.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  1.,  1.,  0.,  1.,  0.,  1.,  0.,  0.,  0.,
        0.,  0.,  1.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  1.,  1.,  0.,  1.,  0.,  0.,  1.,  1.,  0.,  1.,  0.,
        0.,  1.,  0.,  1.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,
        0.,  0.,  1.,  1.,  0.,  1.,  1.,  1.,  1.,  1.,  0.,  1

In [16]:
y_test

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 0., 1., 0., 1., 1.,
       1., 1., 1., 0., 0., 1., 0., 1., 0., 0., 1., 0., 0., 1., 0., 0., 1.,
       1., 0., 1., 1., 1., 0., 0., 1., 1., 0., 1., 1., 1., 0., 0., 1., 0.,
       0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 0., 0.,
       0., 1., 1., 0., 1., 0., 1., 0., 0., 1., 1., 1., 1., 0., 1., 0., 0.,
       0., 0., 1., 1., 0., 0., 0., 1., 1., 0., 1., 1., 0., 0., 0., 1., 0.,
       0., 0., 1., 0., 0., 1., 1., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.,
       0., 1., 0., 1., 0., 1., 0., 1., 1., 0., 1., 1., 0., 0., 0., 0., 0.,
       1., 0., 0., 0., 0., 0., 1., 0., 1., 1., 1., 1., 1., 0., 1., 1., 1.,
       0., 1., 0., 1., 0., 0., 0., 1., 1., 1., 1., 1., 0., 1., 0., 0., 0.,
       0., 0., 0., 1., 0., 0., 1., 1., 0., 0., 0., 0., 1., 0., 1., 0., 1.,
       1., 0., 0., 1., 0., 0., 1., 1., 1., 1., 0., 0., 1., 1., 1., 0., 0.,
       1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1.,
       1., 1., 0., 1., 0.

## Standardizing the Data

Usually when using Neural Networks, you will get better performance when you standardize the data. Standardization just means normalizing the values to all fit between a certain range, like 0-1, or -1 to 1.

The scikit learn library also provides a nice function for this.

http://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.MinMaxScaler.html

In [17]:
from sklearn.preprocessing import MinMaxScaler

In [18]:
scaler_object = MinMaxScaler()

In [19]:
scaler_object.fit(X_train)
#just finds out the min and the max for the data that you want to fit

MinMaxScaler()

In [20]:
scaled_X_train = scaler_object.transform(X_train)
#this operation gives us scaler transformed data

In [21]:
scaled_X_test = scaler_object.transform(X_test)

Ok, now we have the data scaled!

In [22]:
X_train.max()

nan

In [23]:
scaled_X_train.max()

nan

In [24]:
X_train

array([[  0.74428,  -3.7723 ,   1.6131 ,   1.5754 ],
       [  4.6464 ,  10.5326 ,  -4.5852 ,  -4.206  ],
       [ -4.3773 ,  -5.5167 ,  10.939  ,  -0.4082 ],
       ...,
       [ -3.9698 ,   3.6812 ,  -0.60008,  -4.0133 ],
       [ -5.873  ,   9.1752 ,  -0.27448,  -6.0422 ],
       [ -3.5985 , -13.6593 ,  17.6052 ,  -2.4927 ]])

In [25]:
scaled_X_train

array([[0.56150834, 0.37421561, 0.2950746 , 0.92051975],
       [0.84290649, 0.90948448, 0.02725195, 0.39482801],
       [0.19216984, 0.30894266, 0.69803788, 0.74015476],
       ...,
       [0.22155637, 0.65311491, 0.1994452 , 0.41234985],
       [0.08430868, 0.85869252, 0.21351406, 0.22786583],
       [0.24833236, 0.00425823, 0.98607804, 0.55061513]])

## Building the Network with Keras

Let's build a simple neural network!

In [26]:
from keras.models import Sequential
from keras.layers import Dense

In [27]:
# Creates model
model = Sequential()
# 8 Neurons, expects input of 4 features. 
# Play around with the number of neurons!!
model.add(Dense(4, input_dim=4, activation='relu'))
# Add another Densely Connected layer (every neuron connected to every neuron in the next layer)
model.add(Dense(8, activation='relu'))
# Last layer simple sigmoid function to output 0 or 1 (our label)
model.add(Dense(1, activation='sigmoid'))

/opt/conda/lib/python3.10/site-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


### Compile Model

In [28]:
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

## Fit (Train) the Model

In [29]:
# Play around with number of epochs as well!
model.fit(scaled_X_train,y_train,epochs=50, verbose=2)

Epoch 1/50
29/29 - 1s - 48ms/step - accuracy: 0.5495 - loss: nan
Epoch 2/50
29/29 - 0s - 2ms/step - accuracy: 0.5495 - loss: nan
Epoch 3/50
29/29 - 0s - 2ms/step - accuracy: 0.5495 - loss: nan
Epoch 4/50
29/29 - 0s - 2ms/step - accuracy: 0.5495 - loss: nan
Epoch 5/50
29/29 - 0s - 2ms/step - accuracy: 0.5495 - loss: nan
Epoch 6/50
29/29 - 0s - 2ms/step - accuracy: 0.5495 - loss: nan
Epoch 7/50
29/29 - 0s - 2ms/step - accuracy: 0.5495 - loss: nan
Epoch 8/50
29/29 - 0s - 2ms/step - accuracy: 0.5495 - loss: nan
Epoch 9/50
29/29 - 0s - 2ms/step - accuracy: 0.5495 - loss: nan
Epoch 10/50
29/29 - 0s - 2ms/step - accuracy: 0.5495 - loss: nan
Epoch 11/50
29/29 - 0s - 5ms/step - accuracy: 0.5495 - loss: nan
Epoch 12/50
29/29 - 0s - 2ms/step - accuracy: 0.5495 - loss: nan
Epoch 13/50
29/29 - 0s - 2ms/step - accuracy: 0.5495 - loss: nan
Epoch 14/50
29/29 - 0s - 2ms/step - accuracy: 0.5495 - loss: nan
Epoch 15/50
29/29 - 0s - 2ms/step - accuracy: 0.5495 - loss: nan
Epoch 16/50
29/29 - 0s - 2ms/step

## Predicting New Unseen Data

Let's see how we did by predicting on **new data**. Remember, our model has **never** seen the test data that we scaled previously! This process is the exact same process you would use on totally brand new data. For example , a brand new bank note that you just analyzed .

In [30]:
scaled_X_test

array([[0.69174798, 0.33008041, 0.50074104, 0.73944916],
       [0.6107854 , 0.82911314, 0.13465668, 0.59835238],
       [0.66262106, 0.74285586, 0.20040789, 0.57448376],
       ...,
       [0.67021468, 0.32295592, 0.41081004, 0.66372969],
       [0.88584327, 0.90971648, 0.04746514, 0.38812661],
       [0.44485069, 0.51413045, 0.21666098, 0.82798585]])

In [31]:
# Spits out probabilities by default.
# model.predict(scaled_X_test)

In [32]:
# Assuming model is your Keras Sequential model
predictions = model.predict(scaled_X_test)
predicted_classes = np.where(predictions > 0.5, 1, 0)

15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step


In [33]:
# Print the predicted probabilities for the first 5 samples
print(predictions[:5])

[[nan]
 [nan]
 [nan]
 [nan]
 [nan]]


In [34]:
predicted_classes

array([[0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
    

# Evaluating Model Performance

So how well did we do? How do we actually measure "well". Is 95% accuracy good enough? It all depends on the situation. Also we need to take into account things like recall and precision. Make sure to watch the video discussion on classification evaluation before running this code!

In [35]:
model.metrics_names

['loss', 'compile_metrics']

In [36]:
model.evaluate(x=scaled_X_test,y=y_test)

15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.5625 - loss: nan  


[nan, 0.566079318523407]

In [37]:
from sklearn.metrics import confusion_matrix,classification_report

In [38]:
#predictions = model.predict_classes(scaled_X_test)

predictions = model.predict(scaled_X_test)
predicted_classes = np.where(predictions > 0.5, 1, 0)

15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step 


In [39]:
confusion_matrix(y_test,predicted_classes)

array([[257,   0],
       [197,   0]])

In [40]:
print(classification_report(y_test,predicted_classes))

              precision    recall  f1-score   support

         0.0       0.57      1.00      0.72       257
         1.0       0.00      0.00      0.00       197

    accuracy                           0.57       454
   macro avg       0.28      0.50      0.36       454
weighted avg       0.32      0.57      0.41       454



/opt/conda/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/conda/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/conda/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


## Saving and Loading Models

Now that we have a model trained, let's see how we can save and load it.

In [41]:
model.save('myfirstmodel.h5')

In [42]:
from keras.models import load_model

In [43]:
newmodel = load_model('myfirstmodel.h5')

In [44]:
#newmodel.predict_classes(X_test)

#Need to change this code according to the new approach

Great job! You now know how to preprocess data, train a neural network, and evaluate its classification performance!